USE sales_analysis;

SET SQL_SAFE_UPDATES = 0;

-- Update data type of engage_date column of sales_pipeline table
UPDATE sales_pipeline
SET engage_date = STR_TO_DATE(engage_date,'%d-%m-%Y')
WHERE engage_date != '';

-- Update data type of close_date column of sales_pipeline table
UPDATE sales_pipeline
SET close_date = STR_TO_DATE(close_date,'%d-%m-%Y')
WHERE close_date != '';


SELECT * FROM sales_pipeline;

# This query calculates the overall performance metrics of the sales pipeline.
# It returns:
# 1. Total number of opportunities in the pipeline
# 2. Total revenue generated from all deals
# 3. Total number of deals that were successfully won

SELECT 
COUNT(opportunity_id) as opportunities,
SUM(close_value) as revenue,
SUM(CASE WHEN deal_stage='Won' THEN 1 ELSE 0 END) as won
FROM sales_pipeline;

# Shows how revenue grows month by month.

SELECT 
DATE_FORMAT(close_date,'%Y-%m') AS month,
SUM(close_value) AS revenue
FROM sales_pipeline
GROUP BY month
ORDER BY month;

# Shows number of deals in each pipeline stage.

SELECT deal_stage, COUNT(*) AS deals
FROM sales_pipeline
GROUP BY deal_stage;

# Revenue generated by each product.

SELECT product, SUM(close_value) AS revenue
FROM sales_pipeline
GROUP BY product
ORDER BY revenue DESC;

# Top 10 agents generating highest revenue.

SELECT sales_agent, SUM(close_value) AS revenue
FROM sales_pipeline
GROUP BY sales_agent
ORDER BY revenue DESC
LIMIT 10;

# Industry sectors generating highest revenue.

SELECT a.sector, SUM(p.close_value) AS revenue
FROM sales_pipeline p
JOIN accounts a
ON p.account = a.account
GROUP BY a.sector;

# CHART 1 – DEAL STAGE DISTRIBUTION

SELECT deal_stage, COUNT(*) AS deals
FROM sales_pipeline
GROUP BY deal_stage;

# CHART 2 – REVENUE BY REGION

SELECT t.regional_office,
SUM(p.close_value) AS revenue
FROM sales_pipeline p
JOIN sales_team t
ON p.sales_agent = t.sales_agent
GROUP BY t.regional_office
ORDER BY revenue DESC;


# CHART 3 – AVERAGE DEAL SIZE

SELECT product,
AVG(close_value) AS avg_deal_size
FROM sales_pipeline
GROUP BY product
ORDER BY avg_deal_size DESC;

# CHART 4 – WON VS LOST DEALS

SELECT deal_stage, COUNT(*) AS deals
FROM sales_pipeline
WHERE deal_stage IN ('Won','Lost')
GROUP BY deal_stage;

# CHART 5 – AGENT PERFORMANCE TREND

SELECT 
DATE_FORMAT(close_date,'%Y-%m') AS month,
sales_agent,
SUM(close_value) AS revenue
FROM sales_pipeline
GROUP BY month, sales_agent
order by revenue desc
limit 5;

# TOP CUSTOMERS

SELECT account,
SUM(close_value) AS revenue
FROM sales_pipeline
GROUP BY account
ORDER BY revenue DESC
LIMIT 10;